'use client';
import { useMemo, useState } from 'react';
import { Plus, Pencil, Trash2, MessageCircle, ExternalLink, Copy, CheckCircle2, CircleDollarSign, Clock3, AlertTriangle, Globe2 } from 'lucide-react';
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from '@/components/ui/table';
import { Entry, Kind, TODAY, expenseCents, money, prettyDate } from '@/lib/model';
import { Badge, Blank, Choice, SearchBox, options, tone } from './shared';

type Props={entries:Entry[];create:(kind:Kind,date?:string)=>void;edit:(entry:Entry)=>void;remove:(entry:Entry)=>void;save:(entry:Entry)=>Promise<boolean>;busy:boolean};

function actions(entry:Entry,edit:(entry:Entry)=>void,remove:(entry:Entry)=>void){return <div className="action-buttons"><button aria-label={'Editar '+entry.data.title} onClick={()=>edit(entry)}><Pencil/></button><button aria-label={'Remover '+entry.data.title} onClick={()=>remove(entry)}><Trash2/></button></div>;}

export function Campaigns({entries,create,edit,remove}:Props){
 const [selected,setSelected]=useState<string>(''),[contactId,setContactId]=useState(''),[query,setQuery]=useState('');
 const campaigns=entries.filter(e=>e.kind==='campaign').filter(e=>e.data.title.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR')));
 const contacts=entries.filter(e=>e.kind==='contact'&&e.data.status==='Ativo');
 const campaign=campaigns.find(e=>e.id===selected)||campaigns[0];const contact=contacts.find(e=>e.id===contactId)||contacts[0];
 const message=campaign?(campaign.data.message||'').replaceAll('{nome}',contact?.data.name.split(' ')[0]||'cliente').replaceAll('{oferta}',campaign.data.offer||'esta oferta'):'';
 const phone=(contact?.data.phone||'').replace(/\D/g,'');
 function openWhatsApp(){if(!phone)return;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');}
 return <><div className="toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Buscar campanha"/><button className="primary-button" onClick={()=>create('campaign')}><Plus/>Nova campanha</button></div><div className="campaign-layout"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">CAMPANHAS DE OFERTAS</p><h2>Mensagens preparadas</h2></div><Badge tone="gold">{campaigns.length} campanhas</Badge></div>{campaigns.length?campaigns.map(c=><button key={c.id} className={'campaign-row '+(campaign?.id===c.id?'active':'')} onClick={()=>setSelected(c.id)}><span><strong>{c.data.title}</strong><small>{c.data.audience} · {prettyDate(c.data.scheduled)}</small></span><Badge tone={c.data.status==='Concluída'?'green':c.data.status==='Pronta'?'blue':'neutral'}>{c.data.status}</Badge></button>):<Blank title="Nenhuma campanha" message="Crie a primeira mensagem de oferta para os seus contatos." action={()=>create('campaign')}/>}</section><section className="panel message-preview"><div className="panel-heading"><div><p className="eyebrow">PRÉVIA PERSONALIZADA</p><h2>{campaign?.data.title||'Escolha uma campanha'}</h2></div>{campaign&&actions(campaign,edit,remove)}</div>{campaign&&<><div className="preview-controls"><Choice label="Contato da prévia" value={contact?.id||''} onChange={setContactId} options={contacts.map(c=>[c.id,c.data.name])}/></div><div className="whatsapp-phone"><div className="whatsapp-bubble">{message}</div><small>Os campos <b>{'{nome}'}</b> e <b>{'{oferta}'}</b> são preenchidos automaticamente.</small></div><div className="message-actions"><button className="secondary-button" onClick={()=>void navigator.clipboard.writeText(message)}><Copy/>Copiar mensagem</button><button className="whatsapp-button" disabled={!phone} onClick={openWhatsApp}><MessageCircle/>Abrir no WhatsApp</button></div>{!phone&&<div className="notice"><AlertTriangle/><span>Cadastre o WhatsApp deste contato para abrir a conversa. O CRM prepara a mensagem; o envio só acontece após sua confirmação no WhatsApp.</span></div>}</>}</section></div></>;
}

export function Sites({entries,create,edit,remove}:Props){
 const [query,setQuery]=useState(''),[status,setStatus]=useState('all');const all=entries.filter(e=>e.kind==='site');const rows=all.filter(e=>Object.values(e.data).join(' ').toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))&&(status==='all'||e.data.status===status));
 return <><div className="toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Buscar site, página ou texto"/><Choice label="Situação" value={status} onChange={setStatus} options={[["all","Todas as situações"],...options(['Solicitado','Em edição','Aguardando aprovação','Publicado'])]}/><button className="primary-button" onClick={()=>create('site')}><Plus/>Nova alteração</button></div><section className="panel"><div className="summary-strip"><span><strong>{all.length}</strong> alterações registradas</span><span><strong>{all.filter(x=>x.data.status==='Em edição').length}</strong> em edição</span><span><strong>{all.filter(x=>x.data.status==='Aguardando aprovação').length}</strong> aguardando aprovação</span></div>{rows.length?<Table><TableHeader><TableRow><TableHead>Pedido</TableHead><TableHead>Site / página</TableHead><TableHead>Prazo</TableHead><TableHead>Responsável</TableHead><TableHead>Situação</TableHead><TableHead><span className="sr-only">Ações</span></TableHead></TableRow></TableHeader><TableBody>{rows.map(e=><TableRow key={e.id}><TableCell><button className="row-link" onClick={()=>edit(e)}><strong>{e.data.title}</strong></button><small className="table-meta new-copy">“{e.data.newText}”</small></TableCell><TableCell><a className="site-link" href={e.data.url} target="_blank" rel="noreferrer">{e.data.siteName}<ExternalLink/></a><small className="table-meta">{e.data.page}</small></TableCell><TableCell>{prettyDate(e.data.due)}<small className="table-meta">{e.data.priority}</small></TableCell><TableCell>{e.data.owner}</TableCell><TableCell><Badge tone={e.data.status==='Publicado'?'green':e.data.status==='Em edição'?'blue':'gold'}>{e.data.status}</Badge></TableCell><TableCell>{actions(e,edit,remove)}</TableCell></TableRow>)}</TableBody></Table>:<Blank title="Nenhuma alteração encontrada" message="Registre o texto atual, o novo texto e o prazo de cada site." action={()=>create('site')}/>}</section></>;
}

export function Finance({entries,create,edit,remove,save,busy}:Props){
 const [query,setQuery]=useState(''),[status,setStatus]=useState('open');const all=entries.filter(e=>e.kind==='expense');const rows=all.filter(e=>Object.values(e.data).join(' ').toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))&&(status==='all'||status==='open'&&e.data.status!=='Pago'||e.data.status===status)).sort((a,b)=>a.data.due.localeCompare(b.data.due));
 const totals=useMemo(()=>({open:all.filter(e=>e.data.status!=='Pago').reduce((s,e)=>s+expenseCents(e.data.amount),0),overdue:all.filter(e=>e.data.status!=='Pago'&&e.data.due<TODAY).reduce((s,e)=>s+expenseCents(e.data.amount),0),paid:all.filter(e=>e.data.status==='Pago').reduce((s,e)=>s+expenseCents(e.data.amount),0)}),[all]);
 return <><div className="finance-metrics"><section className="finance-card"><CircleDollarSign/><span>A pagar</span><strong>{money(totals.open)}</strong><small>{all.filter(e=>e.data.status!=='Pago').length} contas abertas</small></section><section className="finance-card warning"><AlertTriangle/><span>Em atraso</span><strong>{money(totals.overdue)}</strong><small>Vencidas até hoje</small></section><section className="finance-card"><CheckCircle2/><span>Pago</span><strong>{money(totals.paid)}</strong><small>Registrado neste painel</small></section><section className="finance-card"><Clock3/><span>Próximo vencimento</span><strong>{prettyDate(rows.find(e=>e.data.status!=='Pago')?.data.due||'')}</strong><small>Organize o caixa com antecedência</small></section></div><div className="toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Buscar conta ou fornecedor"/><Choice label="Situação" value={status} onChange={setStatus} options={[["open","Contas em aberto"],["Pendente","Pendentes"],["Agendado","Agendadas"],["Pago","Pagas"],["all","Todas as contas"]]}/><button className="primary-button" onClick={()=>create('expense')}><Plus/>Nova conta</button></div><section className="panel">{rows.length?<Table><TableHeader><TableRow><TableHead>Conta</TableHead><TableHead>Fornecedor</TableHead><TableHead>Vencimento</TableHead><TableHead>Valor</TableHead><TableHead>Situação</TableHead><TableHead><span className="sr-only">Ações</span></TableHead></TableRow></TableHeader><TableBody>{rows.map(e=>{const overdue=e.data.status!=='Pago'&&e.data.due<TODAY;return <TableRow key={e.id}><TableCell><button className="row-link" onClick={()=>edit(e)}><strong>{e.data.title}</strong></button><small className="table-meta">{e.data.category} · {e.data.recurrence}</small></TableCell><TableCell>{e.data.supplier}<small className="table-meta">{e.data.paymentMethod}</small></TableCell><TableCell className={overdue?'overdue-text':''}>{prettyDate(e.data.due)}{overdue&&<small className="table-meta">Em atraso</small>}</TableCell><TableCell><strong>{money(expenseCents(e.data.amount))}</strong></TableCell><TableCell>{e.data.status==='Pago'?<Badge tone="green">Pago</Badge>:<Choice label={'Situação de '+e.data.title} value={e.data.status} onChange={v=>void save({...e,data:{...e.data,status:v}})} options={options(['Pendente','Agendado','Pago'])}/>}</TableCell><TableCell>{actions(e,edit,remove)}</TableCell></TableRow>})}</TableBody></Table>:<Blank title="Nenhuma conta nesta visualização" message="Mude o filtro ou registre uma nova conta a pagar." action={()=>create('expense')}/>}</section><p className="reference-note">O painel organiza compromissos de pagamento. Confirme sempre a quitação no extrato ou no fornecedor.</p></>;
}
