'use client';
import { WalletCards, AlertTriangle, MessageCircle, Globe2, Clock3, ArrowRight, ChevronRight, ArrowDownLeft, TrendingUp } from 'lucide-react';
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from '@/components/ui/table';
import { Entry, money, expenseCents, financialSummary, prettyDate, TODAY } from '@/lib/model';
import { Badge, Blank } from './shared';

export function Metrics({entries}:{entries:Entry[]}){
 const s=financialSummary(entries,'2026-09','Empresa');
 const cards=[['A receber',money(s.receivable),`${s.incomes.filter(x=>x.data.status!=='Recebido').length} recebimentos em aberto`,ArrowDownLeft],['A pagar',money(s.payable),`${s.expenses.filter(x=>x.data.status!=='Pago').length} contas em aberto`,WalletCards],['Saldo previsto',money(s.projected),'Entradas menos saídas de setembro',TrendingUp],['Valores atrasados',money(s.overduePayable+s.overdueReceivable),'Contas e cobranças vencidas',AlertTriangle]] as const;
 return <div className="metric-grid">{cards.map(([label,value,sub,Icon])=><section className="metric" key={label}><div><p>{label}</p><Icon/></div><strong>{value}</strong><small>{sub}</small></section>)}</div>;
}

export default function Dashboard({entries,navigate,edit}:{entries:Entry[];period:string;setPeriod:(p:string)=>void;navigate:(v:string)=>void;edit:(e:Entry)=>void}){
 const tasks=entries.filter(x=>x.kind==='task'&&x.data.due<=TODAY&&x.data.status!=='Concluída').sort((a,b)=>a.data.due.localeCompare(b.data.due));
 const expenses=entries.filter(x=>x.kind==='expense'&&x.data.status!=='Pago').sort((a,b)=>a.data.due.localeCompare(b.data.due));
 const sites=entries.filter(x=>x.kind==='site'&&x.data.status!=='Publicado').slice(0,4);
 return <><Metrics entries={entries}/><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">CAIXA E VENCIMENTOS</p><h2>Próximas contas a pagar</h2></div><button className="text-button" onClick={()=>navigate('finance')}>Abrir financeiro <ArrowRight/></button></div>{expenses.length?<Table><TableHeader><TableRow><TableHead>Conta</TableHead><TableHead>Vencimento</TableHead><TableHead>Valor</TableHead></TableRow></TableHeader><TableBody>{expenses.slice(0,5).map(e=><TableRow key={e.id}><TableCell><button className="row-link" onClick={()=>edit(e)}>{e.data.title}</button><small className="table-meta">{e.data.supplier}</small></TableCell><TableCell className={e.data.due<TODAY?'overdue-text':''}>{prettyDate(e.data.due)}</TableCell><TableCell><strong>{money(expenseCents(e.data.amount))}</strong></TableCell></TableRow>)}</TableBody></Table>:<Blank title="Nenhuma conta em aberto" message="As contas pendentes e agendadas aparecerão aqui."/>}</section><section className="panel today-panel"><div className="panel-heading"><div><p className="eyebrow">NA SUA AGENDA</p><h2>O que pede atenção hoje</h2></div><Clock3/></div>{tasks.slice(0,4).map(t=><button className="agenda-row" key={t.id} onClick={()=>edit(t)}><span className="time">{t.data.time||'—'}</span><div><strong>{t.data.title}</strong><small>{t.data.owner} · {prettyDate(t.data.due)}{t.data.due<TODAY?' · Em atraso':''}</small></div><ChevronRight/></button>)}{!tasks.length&&<Blank title="Tudo em dia" message="Nenhuma tarefa pendente até hoje."/>}<button className="text-button" onClick={()=>navigate('calendar')}>Abrir agenda <ArrowRight/></button></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">SITES E CONTEÚDO</p><h2>Alterações em andamento</h2></div><button className="text-button" onClick={()=>navigate('sites')}>Ver todas <ArrowRight/></button></div>{sites.map(e=><button className="agenda-row" key={e.id} onClick={()=>edit(e)}><Globe2/><div><strong>{e.data.title}</strong><small>{e.data.siteName} · {e.data.page}</small></div><Badge tone={e.data.status==='Em edição'?'blue':'gold'}>{e.data.status}</Badge></button>)}{!sites.length&&<Blank title="Nenhuma alteração aberta" message="Novos pedidos de texto aparecerão aqui."/>}</section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">OFERTAS</p><h2>Campanhas de WhatsApp</h2></div><button className="text-button" onClick={()=>navigate('campaigns')}>Preparar mensagens <ArrowRight/></button></div>{entries.filter(e=>e.kind==='campaign').slice(0,4).map(e=><button className="agenda-row" key={e.id} onClick={()=>edit(e)}><MessageCircle/><div><strong>{e.data.title}</strong><small>{e.data.audience} · {prettyDate(e.data.scheduled)}</small></div><Badge tone={e.data.status==='Pronta'?'blue':e.data.status==='Concluída'?'green':'neutral'}>{e.data.status}</Badge></button>)}</section></div></>;
}
