'use client';
import { Landmark, CheckCircle2, BarChart3, Headphones, Clock3, ArrowRight, ChevronRight, ArrowUpRight } from 'lucide-react';
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from '@/components/ui/table';
import { Entry, money, periodLedger, summarize, ranking, prettyDate, TODAY } from '@/lib/model';
import { Badge, Blank, tone } from './shared';
export function Metrics({period,entries}:{period:string;entries:Entry[]}) {const s=summarize(periodLedger(period)),open=entries.filter(x=>x.kind==='ticket'&&x.data.status!=='Resolvido');const cards=[['Valor líquido histórico',money(s.net),'Receita bruta menos estornos',Landmark],['Registros concluídos',String(s.validCount),'Exclui registros estornados',CheckCircle2],['Valor médio por registro',money(s.ticket),'Média dos registros concluídos',BarChart3],['Atendimentos abertos',String(open.length),open.filter(x=>x.data.status==='Em andamento').length+' em andamento',Headphones]] as const;return <div className="metric-grid">{cards.map(([label,value,sub,Icon])=><section className="metric" key={label}><div><p>{label}</p><Icon/></div><strong>{value}</strong><small>{sub}</small></section>)}</div>;}
export function RevenueChart({period,setPeriod}:{period:string;setPeriod:(p:string)=>void}) {const months=['04','05','06','07','08','09'];const totals=months.map(m=>summarize(periodLedger('2026-'+m)).net);const max=Math.max(...totals);return <section className="panel revenue-panel"><div className="panel-heading"><div><h2>Histórico financeiro</h2><p>Valores líquidos registrados · abril a setembro</p></div><Badge tone="gold">Dados fictícios</Badge></div><fieldset className="bar-chart" aria-label="Histórico financeiro mensal">{months.map((m,i)=><div key={m} className={'chart-column '+(period==='2026-'+m?'selected':'')}><span>{money(totals[i])}</span><button title={money(totals[i])} aria-label={`${['Abril','Maio','Junho','Julho','Agosto','Setembro'][i]}: ${money(totals[i])}. Filtrar mês.`} onClick={()=>setPeriod('2026-'+m)} style={{height:Math.max(12,totals[i]/max*155)+'px'}}/><small>{['Abr','Mai','Jun','Jul','Ago','Set'][i]}</small></div>)}</fieldset><div className="chart-caption"><span><i/>Valor líquido</span><small>Setembro: registros até 08/09</small></div></section>;}
export function RankPanel({period}:{period:string}) {const rows=periodLedger(period),s=summarize(rows);return <section className="panel"><div className="panel-heading"><div><h2>Participação por linha</h2><p>Comparação histórica no período selecionado</p></div><ArrowUpRight/></div>{ranking(rows).map((r,i)=><div className="ranking" key={r.name}><span className="rank-no">0{i+1}</span><div><div><strong>{r.name}</strong><span>{money(r.net)}</span></div><div className="track"><i style={{width:(s.net?r.net/s.net*100:0)+'%'}}/></div><small>{r.units} unidades · {s.net?(r.net/s.net*100).toFixed(1):0}% do valor líquido</small></div></div>)}</section>;}
export default function Dashboard({entries,period,setPeriod,navigate,edit}:{entries:Entry[];period:string;setPeriod:(p:string)=>void;navigate:(v:string)=>void;edit:(e:Entry)=>void}){const tasks=entries.filter(x=>x.kind==='task'&&x.data.due<=TODAY&&x.data.status!=='Concluída').sort((a,b)=>a.data.due.localeCompare(b.data.due)||a.data.time.localeCompare(b.data.time));return <><Metrics entries={entries} period={period}/><div className="dashboard-grid"><RevenueChart period={period} setPeriod={setPeriod}/><section className="panel today-panel"><div className="panel-heading"><div><p className="eyebrow">NA SUA AGENDA</p><h2>O que pede atenção</h2></div><Clock3/></div>{tasks.slice(0,3).map(t=><button className="agenda-row" key={t.id} onClick={()=>edit(t)}><span className="time">{t.data.time||'—'}</span><div><strong>{t.data.title}</strong><small>{t.data.owner} · {prettyDate(t.data.due)}{t.data.due<TODAY?' · Em atraso':''}</small></div><ChevronRight/></button>)}{!tasks.length&&<Blank title="Tudo em dia" message="Nenhuma tarefa pendente até a data de referência."/>}<button className="text-button" onClick={()=>navigate('calendar')}>Abrir agenda completa <ArrowRight/></button></section><RankPanel period={period}/><section className="panel"><div className="panel-heading"><div><h2>Atendimentos recentes</h2><p>Acompanhe cada solicitação</p></div><button className="text-button" onClick={()=>navigate('support')}>Ver todos <ArrowRight/></button></div><Table><TableHeader><TableRow><TableHead>Solicitação</TableHead><TableHead>Situação</TableHead></TableRow></TableHeader><TableBody>{entries.filter(x=>x.kind==='ticket').slice(0,4).map(t=><TableRow key={t.id}><TableCell><button className="row-link" onClick={()=>edit(t)}>{t.data.title}</button><small className="table-meta">{t.data.owner} · {prettyDate(t.data.due)}</small></TableCell><TableCell><Badge tone={tone(t.data.status)}>{t.data.status}</Badge></TableCell></TableRow>)}</TableBody></Table></section></div></>;}
