'use client';
import { useState } from 'react';
import { Save, Pencil, Plus } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Entry, Kind, OWNERS, SOURCES, CONTACT_TYPES, STATUSES, TODAY, initials, prettyDate } from '@/lib/model';
import { Choice, options, Badge, tone } from './shared';
export type Draft={kind:Kind;entry?:Entry;date?:string};
export function Editor({draft,entries,onClose,onSave,busy}:{draft:Draft;entries:Entry[];onClose:()=>void;onSave:(kind:Kind,data:Record<string,string>,entry?:Entry)=>Promise<boolean>;busy:boolean}) {
 const initial:Record<string,string>=draft.kind==='contact'?{name:'',email:'',phone:'',city:'',company:'',type:'Contato',source:'Contato direto',owner:'Hugo',status:'Ativo',notes:'',created:TODAY}:draft.kind==='ticket'?{title:'',contactId:'',status:'Novo',priority:'Normal',owner:'Hugo',due:draft.date||TODAY,channel:'E-mail',description:''}:{title:'',due:draft.date||TODAY,time:'09:00',owner:'Hugo',priority:'Normal',status:'Pendente',category:'Administrativo',description:''};
 const [data,setData]=useState(draft.entry?.data??initial);const [error,setError]=useState('');
 const set=(key:string)=>(value:string)=>setData(d=>({...d,[key]:value}));
 function input(key:string,label:string,type='text',required=false,full=false){return <label className={'field '+(full?'full-field':'')} key={key}>{label}{type==='textarea'?<textarea value={data[key]||''} onChange={e=>set(key)(e.target.value)} maxLength={4000}/>:<input type={type} required={required} value={data[key]||''} onChange={e=>set(key)(e.target.value)} maxLength={key==='name'||key==='title'?160:300}/>}</label>;}
 function choice(key:string,label:string,opts:string[][]){return <div className="field" key={key}><span>{label}</span><Choice value={data[key]||''} label={label} onChange={set(key)} options={opts}/></div>;}
 const noun=draft.kind==='contact'?'contato':draft.kind==='ticket'?'atendimento':'tarefa';
 return <Dialog open onOpenChange={open=>!open&&!busy&&onClose()}><DialogContent className="edit-dialog"><DialogHeader><DialogTitle>{draft.entry?'Editar':'Novo'} {noun}</DialogTitle><DialogDescription>Dados desta demonstração. Nenhuma mensagem será enviada.</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();setError('');if(await onSave(draft.kind,data,draft.entry))onClose();else setError('Confira a mensagem exibida e tente novamente.');}}><fieldset disabled={busy}><div className="form-grid">{draft.kind==='contact'?<>{input('name','Nome completo *','text',true)}{input('email','E-mail *','email',true)}{input('phone','Telefone','tel')}{input('city','Cidade / UF')}{input('company','Empresa ou organização')}{choice('type','Tipo',options(CONTACT_TYPES))}{choice('source','Origem do contato',options(SOURCES))}{choice('owner','Responsável',options(OWNERS))}{choice('status','Situação',options(['Ativo','Arquivado']))}{input('notes','Observações','textarea',false,true)}</>:<>{input('title','Título *','text',true,true)}{draft.kind==='ticket'&&choice('contactId','Contato vinculado',[['','Sem vínculo'],...entries.filter(e=>e.kind==='contact').map(e=>[e.id,e.data.name])])}{choice('owner','Responsável',options(OWNERS))}{input('due','Prazo','date')}{draft.kind==='task'&&input('time','Horário','time')}{choice('priority','Prioridade',options(['Baixa','Normal','Alta']))}{choice('status','Situação',options(draft.kind==='ticket'?STATUSES:['Pendente','Concluída']))}{draft.kind==='ticket'?choice('channel','Canal',options(['E-mail','Site','Telefone','Presencial'])):choice('category','Categoria',options(['Administrativo','Atendimento','Cadastro','Financeiro','Reunião']))}{input('description','Descrição','textarea',false,true)}</>}</div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="secondary-button" type="button" onClick={onClose}>Cancelar</button><button className="primary-button" type="submit"><Save/>{busy?'Salvando…':'Salvar '+noun}</button></div></fieldset></form></DialogContent></Dialog>;
}
export function ContactDetail({entry,entries,onClose,onEdit,onNote,busy}:{entry:Entry;entries:Entry[];onClose:()=>void;onEdit:(e:Entry)=>void;onNote:(contactId:string,text:string)=>Promise<boolean>;busy:boolean}){const [note,setNote]=useState('');const notes=entries.filter(e=>e.kind==='note'&&e.data.contactId===entry.id);const tickets=entries.filter(e=>e.kind==='ticket'&&e.data.contactId===entry.id);return <Sheet open onOpenChange={open=>!open&&onClose()}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>Ficha do contato</SheetTitle><SheetDescription>Cadastro e histórico de atendimento.</SheetDescription></SheetHeader><div className="detail-profile"><span className="avatar">{initials(entry.data.name)}</span><div><h2>{entry.data.name}</h2><small>{entry.data.type} · {entry.data.company}</small></div></div><div><Badge tone={tone(entry.data.status)}>{entry.data.status}</Badge><button className="text-button" style={{marginLeft:15}} onClick={()=>onEdit(entry)}><Pencil/>Editar cadastro</button></div><div className="detail-fields">{[['E-mail',entry.data.email],['Telefone',entry.data.phone||'Não informado'],['Cidade',entry.data.city||'Não informada'],['Responsável',entry.data.owner],['Origem',entry.data.source],['Cadastrado em',prettyDate(entry.data.created)]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{entry.data.notes&&<div className="contact-observation"><h3>Observações</h3><p>{entry.data.notes}</p></div>}<h3>Atendimentos vinculados <Badge>{tickets.length}</Badge></h3>{tickets.length?tickets.map(t=><button className="linked-ticket" key={t.id} onClick={()=>onEdit(t)}><span>{t.data.title}</span><Badge tone={tone(t.data.status)}>{t.data.status}</Badge></button>):<p className="muted-text">Nenhum atendimento vinculado.</p>}<h3 style={{marginTop:18}}>Anotações</h3><form onSubmit={async e=>{e.preventDefault();if(note.trim()&&await onNote(entry.id,note))setNote('');}}><label className="field"><span className="sr-only">Nova anotação</span><textarea placeholder="Registre um contexto importante…" maxLength={4000} value={note} onChange={e=>setNote(e.target.value)} required/></label><button className="primary-button" style={{marginTop:10}} disabled={busy||!note.trim()}><Plus/>Adicionar anotação</button></form>{notes.map(n=><div className="note" key={n.id}><small>{n.data.author} · {new Date(n.updatedAt).toLocaleString('pt-BR')}</small><p>{n.data.text}</p></div>)}</SheetContent></Sheet>;}
