'use client';
import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowDownLeft, ArrowUpRight, Banknote, CheckCircle2, Pencil, Plus, Trash2, TrendingUp, WalletCards } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from '@/components/ui/table';
import { Entry, Kind, TODAY, expenseCents, financialSummary, money, prettyDate } from '@/lib/model';
import { Badge, Blank, Choice, SearchBox, options } from './shared';

type Props={entries:Entry[];create:(kind:Kind,date?:string)=>void;edit:(entry:Entry)=>void;remove:(entry:Entry)=>void;save:(entry:Entry)=>Promise<boolean>;busy:boolean};
const MONTHS=[['2026-09','Setembro 2026'],['2026-08','Agosto 2026'],['all','Todos os períodos']];

function RowActions({entry,edit,remove}:{entry:Entry;edit:(entry:Entry)=>void;remove:(entry:Entry)=>void}){return <div className="action-buttons"><button aria-label={'Editar '+entry.data.title} onClick={()=>edit(entry)}><Pencil/></button><button aria-label={'Remover '+entry.data.title} onClick={()=>remove(entry)}><Trash2/></button></div>}
function statusTone(entry:Entry){if(entry.data.status==='Pago'||entry.data.status==='Recebido')return 'green';if(entry.data.due<TODAY)return 'red';if(entry.data.status==='Agendado')return 'blue';return 'gold'}

export default function Finance({entries,create,edit,remove,save,busy}:Props){
 const [tab,setTab]=useState('summary'),[month,setMonth]=useState('2026-09'),[scope,setScope]=useState('Empresa'),[query,setQuery]=useState('');
 const summary=useMemo(()=>financialSummary(entries,month,scope),[entries,month,scope]);
 const matches=(entry:Entry)=>Object.values(entry.data).join(' ').toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'));
 const expenses=summary.expenses.filter(matches).sort((a,b)=>a.data.due.localeCompare(b.data.due));
 const incomes=summary.incomes.filter(matches).sort((a,b)=>a.data.due.localeCompare(b.data.due));
 const movements=[...expenses,...incomes].sort((a,b)=>a.data.due.localeCompare(b.data.due));
 const openMovements=movements.filter(entry=>entry.kind==='expense'?entry.data.status!=='Pago':entry.data.status!=='Recebido');
 async function settle(entry:Entry){const income=entry.kind==='income';await save({...entry,data:{...entry.data,scope:entry.data.scope||'Empresa',competence:entry.data.competence||entry.data.due.slice(0,7),status:income?'Recebido':'Pago',[income?'receivedDate':'paidDate']:TODAY}})}
 return <>
  <div className="finance-metrics">
   <section className="finance-card income-card"><ArrowDownLeft/><span>A receber</span><strong>{money(summary.receivable)}</strong><small>{summary.incomes.filter(e=>e.data.status!=='Recebido').length} recebimentos em aberto</small></section>
   <section className="finance-card"><ArrowUpRight/><span>A pagar</span><strong>{money(summary.payable)}</strong><small>{summary.expenses.filter(e=>e.data.status!=='Pago').length} contas em aberto</small></section>
   <section className={'finance-card '+(summary.projected<0?'warning':'positive')}><TrendingUp/><span>Saldo previsto</span><strong>{money(summary.projected)}</strong><small>Receitas menos despesas do período</small></section>
   <section className="finance-card"><Banknote/><span>Saldo realizado</span><strong>{money(summary.realized)}</strong><small>Somente valores recebidos e pagos</small></section>
  </div>
  {(summary.overduePayable>0||summary.overdueReceivable>0)&&<div className="finance-alert"><AlertTriangle/><div><strong>Atenção aos atrasos</strong><span>{summary.overduePayable>0&&`${money(summary.overduePayable)} em contas vencidas`}{summary.overduePayable>0&&summary.overdueReceivable>0?' · ':''}{summary.overdueReceivable>0&&`${money(summary.overdueReceivable)} ainda não recebidos`}</span></div></div>}
  <div className="toolbar finance-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Buscar lançamento, cliente ou fornecedor"/><Choice label="Período financeiro" value={month} onChange={setMonth} options={MONTHS}/><Choice label="Centro financeiro" value={scope} onChange={setScope} options={[["Empresa","Empresa"],["Pessoal","Pessoal"],["all","Empresa + pessoal"]]}/><button className="secondary-button" onClick={()=>create('income')}><Plus/>Nova receita</button><button className="primary-button" onClick={()=>create('expense')}><Plus/>Nova despesa</button></div>
  <Tabs value={tab} onValueChange={value=>setTab(String(value))} className="tabs-bar"><TabsList variant="line"><TabsTrigger value="summary">Resumo</TabsTrigger><TabsTrigger value="payable">Contas a pagar ({expenses.length})</TabsTrigger><TabsTrigger value="receivable">Contas a receber ({incomes.length})</TabsTrigger><TabsTrigger value="cashflow">Fluxo de caixa</TabsTrigger></TabsList></Tabs>
  {tab==='summary'&&<div className="finance-summary-grid"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">VISÃO DO PERÍODO</p><h2>Previsto x realizado</h2></div><Badge tone={summary.projected>=0?'green':'red'}>{summary.projected>=0?'Caixa positivo':'Caixa negativo'}</Badge></div><div className="cash-summary"><div><span>Receitas previstas</span><strong className="income-text">{money(summary.incomes.reduce((sum,e)=>sum+expenseCents(e.data.amount),0))}</strong></div><div><span>Despesas previstas</span><strong className="expense-text">− {money(summary.expenses.reduce((sum,e)=>sum+expenseCents(e.data.amount),0))}</strong></div><div className="cash-total"><span>Resultado previsto</span><strong>{money(summary.projected)}</strong></div><div><span>Já recebido</span><strong>{money(summary.received)}</strong></div><div><span>Já pago</span><strong>− {money(summary.paid)}</strong></div><div className="cash-total"><span>Resultado realizado</span><strong>{money(summary.realized)}</strong></div></div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">PRÓXIMOS MOVIMENTOS</p><h2>O que exige ação</h2></div><Badge>{openMovements.length} pendências</Badge></div>{openMovements.slice(0,6).map(entry=><button className="finance-next" key={entry.id} onClick={()=>edit(entry)}><span className={'movement-icon '+entry.kind}>{entry.kind==='income'?<ArrowDownLeft/>:<ArrowUpRight/>}</span><span><strong>{entry.data.title}</strong><small>{entry.kind==='income'?entry.data.client:entry.data.supplier} · {prettyDate(entry.data.due)}</small></span><b className={entry.kind==='income'?'income-text':'expense-text'}>{entry.kind==='income'?'+':'−'} {money(expenseCents(entry.data.amount))}</b></button>)}{!openMovements.length&&<Blank title="Nenhuma pendência" message="Tudo recebido ou pago neste período."/>}</section></div>}
  {tab==='payable'&&<FinanceTable rows={expenses} type="expense" edit={edit} remove={remove} settle={settle} busy={busy} create={()=>create('expense')}/>}
  {tab==='receivable'&&<FinanceTable rows={incomes} type="income" edit={edit} remove={remove} settle={settle} busy={busy} create={()=>create('income')}/>}
  {tab==='cashflow'&&<CashFlow rows={movements}/>} 
  <p className="reference-note">Os valores são controles internos. Confirme pagamentos e recebimentos nos extratos e documentos correspondentes.</p>
 </>
}

function FinanceTable({rows,type,edit,remove,settle,busy,create}:{rows:Entry[];type:'expense'|'income';edit:(entry:Entry)=>void;remove:(entry:Entry)=>void;settle:(entry:Entry)=>Promise<void>;busy:boolean;create:()=>void}){
 const done=type==='expense'?'Pago':'Recebido';
 return <section className="panel">{rows.length?<Table><TableHeader><TableRow><TableHead>{type==='expense'?'Conta':'Receita'}</TableHead><TableHead>{type==='expense'?'Fornecedor':'Cliente / origem'}</TableHead><TableHead>Vencimento</TableHead><TableHead>Valor</TableHead><TableHead>Centro</TableHead><TableHead>Situação</TableHead><TableHead><span className="sr-only">Ações</span></TableHead></TableRow></TableHeader><TableBody>{rows.map(entry=>{const overdue=entry.data.status!==done&&entry.data.due<TODAY;return <TableRow key={entry.id}><TableCell><button className="row-link" onClick={()=>edit(entry)}><strong>{entry.data.title}</strong></button><small className="table-meta">{entry.data.category} · {entry.data.recurrence}</small></TableCell><TableCell>{type==='expense'?entry.data.supplier:entry.data.client}<small className="table-meta">{entry.data.paymentMethod}</small></TableCell><TableCell className={overdue?'overdue-text':''}>{prettyDate(entry.data.due)}{overdue&&<small className="table-meta">Em atraso</small>}</TableCell><TableCell><strong>{money(expenseCents(entry.data.amount))}</strong></TableCell><TableCell><Badge>{entry.data.scope||'Empresa'}</Badge></TableCell><TableCell>{entry.data.status===done?<Badge tone="green">{done}</Badge>:<div className="settle-cell"><Badge tone={statusTone(entry)}>{overdue?'Em atraso':entry.data.status}</Badge><button className="text-button" disabled={busy} onClick={()=>void settle(entry)}><CheckCircle2/>Marcar {type==='expense'?'pago':'recebido'}</button></div>}</TableCell><TableCell><RowActions entry={entry} edit={edit} remove={remove}/></TableCell></TableRow>})}</TableBody></Table>:<Blank title={type==='expense'?'Nenhuma conta neste período':'Nenhuma receita neste período'} message="Mude os filtros ou adicione um novo lançamento." action={create}/>}</section>
}

function CashFlow({rows}:{rows:Entry[]}){
 let balance=0;
 return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">FLUXO DE CAIXA PREVISTO</p><h2>Linha do tempo financeira</h2></div><WalletCards/></div>{rows.length?<Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Movimento</TableHead><TableHead>Tipo</TableHead><TableHead>Entrada</TableHead><TableHead>Saída</TableHead><TableHead>Saldo acumulado</TableHead></TableRow></TableHeader><TableBody>{rows.map(entry=>{const value=expenseCents(entry.data.amount),income=entry.kind==='income';balance+=income?value:-value;return <TableRow key={entry.id}><TableCell>{prettyDate(entry.data.due)}</TableCell><TableCell><strong>{entry.data.title}</strong><small className="table-meta">{income?entry.data.client:entry.data.supplier}</small></TableCell><TableCell><Badge tone={income?'green':'red'}>{income?'Entrada':'Saída'}</Badge></TableCell><TableCell className="income-text">{income?money(value):'—'}</TableCell><TableCell className="expense-text">{income?'—':money(value)}</TableCell><TableCell><strong className={balance<0?'expense-text':'income-text'}>{money(balance)}</strong></TableCell></TableRow>})}</TableBody></Table>:<Blank title="Sem movimentos no período" message="Adicione receitas e despesas para visualizar o fluxo de caixa."/>}</section>
}
