'use client';
import { useRef, useState } from 'react';
import { Database, ShieldCheck, BookOpen, Download, CheckCircle2, RefreshCw, MessageCircle, Globe2, WalletCards, Users, Upload } from 'lucide-react';
import { ImportResult } from '@/lib/client-store';
import { Entry, Activity } from '@/lib/model';
import { Badge, download, Blank } from './shared';
const guides=[{icon:Users,title:'Contatos completos',text:'Mantenha cadastro, WhatsApp, origem e contexto de cada pessoa.',steps:['Cadastre o telefone com DDD.','Registre preferências e observações.','Arquive quem não deve receber contato.']},{icon:MessageCircle,title:'Ofertas no WhatsApp',text:'Crie uma mensagem-base e personalize com o primeiro nome e a oferta.',steps:['Use {nome} e {oferta} no texto.','Confira a prévia por contato.','Revise e confirme o envio no WhatsApp.']},{icon:Globe2,title:'Sites e textos',text:'Organize pedidos de alteração sem perder a versão anterior.',steps:['Informe site e página.','Guarde o texto atual e o novo.','Acompanhe prazo, aprovação e publicação.']},{icon:WalletCards,title:'Contas a pagar',text:'Centralize o que vence, o que atrasou e o que já foi pago.',steps:['Cadastre valor e vencimento.','Defina recorrência e forma de pagamento.','Marque como pago após conferir a quitação.']}];
type Importer=(payload:unknown,removeDemo:boolean)=>Promise<ImportResult>;
function ImportBase({refresh,busy,onImport,remote}:{refresh:()=>void;busy:boolean;onImport:Importer;remote:boolean}){
 const input=useRef<HTMLInputElement>(null);const [removeDemo,setRemoveDemo]=useState(true);const [result,setResult]=useState<ImportResult|null>(null);const [error,setError]=useState('');const [working,setWorking]=useState(false);
 async function pick(file:File|undefined){if(!file)return;setWorking(true);setError('');setResult(null);try{if(file.size>20_000_000)throw new Error('Arquivo grande demais.');const payload=JSON.parse(await file.text());const r=await onImport(payload,removeDemo);setResult(r);refresh();}catch(e){setError(e instanceof DOMException&&e.name==='QuotaExceededError'?'O navegador não tem espaço para esta base.':e instanceof Error?e.message:'Não foi possível importar.');}finally{setWorking(false);if(input.current)input.current.value='';}}
 return <div className="settings-row" style={{flexWrap:'wrap',gap:12}}><div style={{flex:'1 1 320px'}}><p>Importar base de clientes</p><small>Carrega o arquivo de clientes revisado (Wix + WooCommerce + planilha). {remote?'Os clientes vão para o banco do CRM e aparecem em todos os aparelhos logados.':'Os dados ficam salvos só neste navegador — faça o backup depois.'} Contatos com o mesmo e-mail são atualizados, não duplicados, e o que já foi editado no CRM é mantido.</small>{!remote&&<label style={{display:'flex',gap:8,alignItems:'center',marginTop:8,fontSize:13}}><input type="checkbox" checked={removeDemo} onChange={e=>setRemoveDemo(e.target.checked)}/>Remover os dados fictícios de demonstração</label>}{result&&<small style={{display:'block',marginTop:8}}><strong>{result.created}</strong> contatos novos · <strong>{result.updated}</strong> atualizados{result.removedDemo?<> · {result.removedDemo} registros de demonstração removidos</>:null}{result.errors.length?<> · <strong>{result.errors.length}</strong> com erro: {result.errors.slice(0,5).map(x=>`${x.name||'linha '+x.row} (${x.error})`).join('; ')}</>:null}</small>}{error&&<small style={{display:'block',marginTop:8,color:'#b3261e'}}>{error}</small>}</div><input ref={input} type="file" accept="application/json,.json" hidden onChange={e=>void pick(e.target.files?.[0])}/><button className="primary-button" onClick={()=>input.current?.click()} disabled={busy||working}><Upload/>{working?'Importando…':'Escolher arquivo'}</button></div>;
}
export default function Help({entries,activity,refresh,busy,remote=false,onImport}:{entries:Entry[];activity:Activity[];refresh:()=>void;busy:boolean;remote?:boolean;onImport?:Importer}){return <><section className="panel help-card" style={{marginBottom:22}}><div className="panel-heading" style={{padding:0}}><div><p className="eyebrow">SOBRE ESTE AMBIENTE</p><h2>O centro de controle do negócio do Hugo.</h2></div><Badge tone="green">Dados persistentes</Badge></div><p style={{marginTop:15}}>Contatos, mensagens, alterações de sites, contas, tarefas e anotações ficam salvos e entram no histórico.</p><div className="settings-row"><div><p>Envio pelo WhatsApp</p><small>O CRM personaliza a mensagem e abre a conversa. Hugo revisa e confirma o envio no WhatsApp.</small></div><Badge>Assistido</Badge></div><div className="settings-row"><div><p>Dados salvos</p><small>{entries.length} registros administrativos neste ambiente.</small></div><button className="secondary-button" onClick={refresh} disabled={busy}><RefreshCw/>Atualizar</button></div><div className="settings-row"><div><p>Cópia de segurança</p><small>Baixe contatos, contas, campanhas, sites, tarefas e histórico em um arquivo.</small></div><button className="secondary-button" onClick={()=>download(JSON.stringify({version:2,exportedAt:new Date().toISOString(),entries,activity},null,2),'crm-hugo-backup.json','application/json')}><Download/>Baixar dados</button></div>{onImport&&<ImportBase refresh={refresh} busy={busy} onImport={onImport} remote={remote}/>}<div className="notice" style={{marginTop:18,marginBottom:0}}><ShieldCheck/><span>Antes de cadastrar dados reais, defina quem terá acesso e mantenha consentimento e preferências de contato atualizados.</span></div></section><div className="help-grid">{guides.map(({icon:Icon,title,text,steps})=><section className="panel help-card" key={title}><Icon/><h2>{title}</h2><p>{text}</p><ul>{steps.map(s=><li key={s}>{s}</li>)}</ul></section>)}<section className="panel help-card"><BookOpen/><h2>Rotina recomendada</h2><ol className="guide-steps"><li>Comece pela visão geral e trate contas atrasadas.</li><li>Revise campanhas e confira a mensagem de cada contato.</li><li>Acompanhe textos de sites aguardando aprovação.</li><li>Atualize tarefas e atendimentos do dia.</li><li>Exporte o relatório de contas para conferência.</li></ol></section><section className="panel help-card"><Database/><h2>O que já funciona</h2><ul><li>Criação e edição persistente de registros.</li><li>Campanhas com personalização por nome e oferta.</li><li>Controle de textos e aprovações de sites.</li><li>Contas a pagar, atrasos, recorrências e baixas.</li><li>Agenda, atendimentos, histórico e exportações.</li></ul><p>Integrações automáticas com bancos, WordPress e API oficial do WhatsApp podem ser adicionadas quando as contas e permissões forem definidas.</p></section></div></>}
export function ActivityLog({activity}:{activity:Activity[]}){return <section className="panel"><div className="panel-heading"><div><h2>Histórico de alterações</h2><p>As 200 alterações mais recentes do CRM</p></div><Badge>{activity.length} eventos</Badge></div>{!activity.length?<Blank title="Nenhuma alteração registrada" message="Crie ou atualize um registro para começar o histórico."/>:<div className="timeline">{activity.map(a=><div className="timeline-entry" key={a.id}><CheckCircle2/><div><strong>{a.action}</strong><p>{a.label}</p><small>{new Date(a.created_at).toLocaleString('pt-BR')}</small></div></div>)}</div>}</section>}
