'use client';
import { Download, Printer } from 'lucide-react';
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from '@/components/ui/table';
import { Entry, expenseCents, financialSummary, money, prettyDate } from '@/lib/model';
import { Badge, exportCsv } from './shared';
import { Metrics } from './dashboard';
export default function Reports({entries}:{period:string;setPeriod:(v:string)=>void;entries:Entry[]}){
 const rows=entries.filter(e=>e.kind==='expense'||e.kind==='income').sort((a,b)=>a.data.due.localeCompare(b.data.due)),summary=financialSummary(entries,'all','Empresa');
 function exportData(){exportCsv([['Tipo','Descrição','Cliente/Fornecedor','Categoria','Valor (R$)','Vencimento','Recorrência','Centro','Situação'],...rows.map(e=>[e.kind==='income'?'Receita':'Despesa',e.data.title,e.kind==='income'?e.data.client:e.data.supplier,e.data.category,(expenseCents(e.data.amount)/100).toFixed(2),e.data.due,e.data.recurrence,e.data.scope||'Empresa',e.data.status])],'relatorio-financeiro-hugo.csv')}
 return <><div className="toolbar"><span className="spacer"/><button className="secondary-button" onClick={exportData}><Download/>Exportar financeiro</button><button className="secondary-button" onClick={()=>window.print()}><Printer/>Imprimir</button></div><Metrics entries={entries}/><div className="report-grid"><section className="panel"><div className="panel-heading"><h2>Resultado acumulado da empresa</h2><Badge tone={summary.projected>=0?'green':'red'}>{summary.projected>=0?'Positivo':'Negativo'}</Badge></div><div className="cash-summary"><div><span>Total de receitas</span><strong className="income-text">{money(summary.received+summary.receivable)}</strong></div><div><span>Total de despesas</span><strong className="expense-text">− {money(summary.paid+summary.payable)}</strong></div><div className="cash-total"><span>Resultado previsto</span><strong>{money(summary.projected)}</strong></div><div className="cash-total"><span>Resultado realizado</span><strong>{money(summary.realized)}</strong></div></div></section><section className="panel"><div className="panel-heading"><h2>Pendências financeiras</h2></div><div className="cash-summary"><div><span>A receber</span><strong>{money(summary.receivable)}</strong></div><div><span>A pagar</span><strong>{money(summary.payable)}</strong></div><div><span>Recebimentos atrasados</span><strong className="expense-text">{money(summary.overdueReceivable)}</strong></div><div><span>Pagamentos atrasados</span><strong className="expense-text">{money(summary.overduePayable)}</strong></div></div></section></div><section className="panel" style={{marginTop:22}}><div className="panel-heading"><div><h2>Todos os lançamentos</h2><p>Receitas e despesas registradas no CRM</p></div><Badge tone="gold">{rows.length} registros</Badge></div><Table><TableHeader><TableRow><TableHead>Tipo</TableHead><TableHead>Descrição</TableHead><TableHead>Cliente / fornecedor</TableHead><TableHead>Vencimento</TableHead><TableHead>Valor</TableHead><TableHead>Centro</TableHead><TableHead>Situação</TableHead></TableRow></TableHeader><TableBody>{rows.map(e=><TableRow key={e.id}><TableCell><Badge tone={e.kind==='income'?'green':'red'}>{e.kind==='income'?'Receita':'Despesa'}</Badge></TableCell><TableCell><strong>{e.data.title}</strong><small className="table-meta">{e.data.category}</small></TableCell><TableCell>{e.kind==='income'?e.data.client:e.data.supplier}</TableCell><TableCell>{prettyDate(e.data.due)}</TableCell><TableCell>{money(expenseCents(e.data.amount))}</TableCell><TableCell>{e.data.scope||'Empresa'}</TableCell><TableCell><Badge tone={e.data.status==='Pago'||e.data.status==='Recebido'?'green':'gold'}>{e.data.status}</Badge></TableCell></TableRow>)}</TableBody></Table></section><p className="reference-note">Use a exportação para conferência com extratos, notas e documentos dos clientes e fornecedores.</p></>;
}
